version: '3.3'
services:
  rabbitmq:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password_1234
      RABBITMQ_DEFAULT_VHOST: test
    ports:
      - 5672:5672